name: Set Keycloak Image Name
description: Set the Keycloak image name based on the Keycloak version using the needs:read-build-image-output step.
author: Camunda
inputs:
  keycloak_version:
    description: Keycloak version
    required: true
outputs:
  keycloak_image_name:
    description: Keycloak image name
runs:
  using: "composite"
  steps:
    - name: Set Keycloak Image Name
      id: set-keycloak-image-name
      run: |
        keycloak_image_name="${{ fromJson(needs.read-build-image-output.outputs.result).full_image_name[inputs.keycloak_version] }}"
        echo "keycloak_image_name=${keycloak_image_name}" >> "$GITHUB_ENV"
        echo "keycloak_image_name=${keycloak_image_name}"
