version: '3'

volumes:
  postgres_data:
      driver: local

services:
  postgres:
      image: postgres
      volumes:
        - postgres_data:/var/lib/postgresql/data
      environment:
        POSTGRES_DB: keycloak
        POSTGRES_USER: keycloak
        POSTGRES_PASSWORD: password
      healthcheck:
        test: ["CMD-SHELL", "PGPASSWORD=$${POSTGRES_PASSWORD} psql --username=$${POSTGRES_USER} --host=localhost --dbname=$${POSTGRES_DB} --command='\\q'"]
        interval: 30s
        timeout: 5s
        retries: 3
  keycloak:
      image: langleu/keycloak:latest
      build: .
      command: start-dev
      environment:
        KEYCLOAK_ADMIN: admin
        KEYCLOAK_ADMIN_PASSWORD: admin
        KC_DB_USERNAME: keycloak
        KC_DB_PASSWORD: password
        KC_DB_DRIVER: software.amazon.jdbc.Driver
        KC_TRANSACTION_XA_ENABLED: false
        KC_DB_URL: jdbc:aws-wrapper:postgresql://postgres:5432/keycloak
      healthcheck:
        test: timeout 10s bash -c ':> /dev/tcp/127.0.0.1/8080' || exit 1
        interval: 15s
        timeout: 5s
        retries: 5
      ports:
        - 8080:8080
      depends_on:
        - postgres

# /kcadm.sh get clients --realm master --server http://localhost:8080 --user admin --password admin
