# List of all available images with associated sha:
# skopeo --override-os linux inspect docker://dev.registry.camunda.cloud/dockerhub-infraex/bitnamiprem/keycloak
ARG BASE_IMAGE_NAME="dev.registry.camunda.cloud/dockerhub-infraex/bitnamiprem/keycloak:26.2.5-debian-12-r3"

# Note: use the global index image digest to make this image platform agnostic
# skopeo --override-os linux inspect docker://dev.registry.camunda.cloud/dockerhub-infraex/bitnamiprem/keycloak:<tag> --raw | skopeo manifest-digest /dev/stdin
ARG BASE_IMAGE_DIGEST="sha256:17aff522766636a7a315188481662b4bf4ce846731c06da261ba5b6a95fea70d"
