# List of all available images with associated sha:
# skopeo --override-os linux inspect  docker://docker.io/bitnami/keycloak
ARG BASE_IMAGE_NAME="docker.io/bitnami/keycloak:23.0.7-debian-12-r5"

# Note: use the global index image digest to make this image platform agnostic
# skopeo --override-os linux inspect docker://docker.io/bitnami/keycloak:<tag> --raw | skopeo manifest-digest /dev/stdin
ARG BASE_IMAGE_DIGEST="sha256:9596e39ee28105274379903db57aee298ab9f3292aa96797fda2aeaabcc38326"
