---
name: Compose
description: |
    Compose Wrapper
inputs:
    compose_file:
        description: Name of the compose file
        required: false
        default: docker-compose.yml
    project_name:
        description: Project name to allow running the same file multiple times
        required: true
    healthy_timeout:
        description: How long to wait until we consider the compose to be unhealthy
        required: false
        default: '300'
    cwd:
        description: Current working directory
        required: false
        default: ${{ github.workspace }}
runs:
    using: composite
    steps:
        - name: Run ${{ inputs.project_name }} compose
          uses: hoverkraft-tech/compose-action@40041ff1b97dbf152cd2361138c2b03fa29139df # v2.3.0
          with:
              compose-file: |
                  ${{ inputs.compose_file }}
              compose-flags: --project-name ${{ inputs.project_name }}
              cwd: ${{ inputs.cwd }}

        - name: Short sleep to let it startup
          shell: bash
          run: sleep 3

        - name: Check if service is healthy
          shell: bash
          run: |
              ${{ github.action_path }}/healthy.sh
          env:
              FILE: ${{ inputs.cwd }}/${{ inputs.compose_file }}
              TIMEOUT: ${{ inputs.healthy_timeout }}
              COMPOSE_FLAGS: --project-name ${{ inputs.project_name }}
