---
# desc: workflow dedicated to all the pre-commit verifications (lint)

name: lint
on:
 - push
 - pull_request_target

jobs:
  pre-commit:
    name: pre-commit
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v3
    - uses: pre-commit/action@v3.0.0
...
