---
# desc: build container images, perform static tests then push
#       this workflow will only use current as tag container tag reference, dedicated workflow exists for releasing versionned image

name: build-images

on:
  push:

jobs:
  docker-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install if required common software tooling
        uses: camunda/infra-global-github-actions/common-tooling@main
        with:
          java-enabled: false
          yarn-enabled: false

      - name: Build image using Camunda docker build
        uses: camunda/infra-global-github-actions/build-docker-image@feature/container-build-multiarch
        with:
          registry_host: ${{ vars.CONTAINER_REGISTRY }}
          registry_username: ${{ secrets.DOCKERHUB_USERNAME }}
          registry_password: ${{ secrets.DOCKERHUB_TOKEN }}
          force_push: true
          image_name: ${{ vars.CONTAINER_IMAGE_NAME }}
          build_context: .
          build_platforms: linux/amd64,linux/arm64

      - name: Test built images
        uses: ./.github/workflows/30-test-images.yml
