---
# desc: build container images, perform static tests then push

name: test-images

on:
  workflow_call:
    inputs:
      test_image_name:
        description: "Fully qualified image name with registry and tag (e.g. `docker.io/myuser/myimage:feature@sha256:378738...`)"
        required: true
        type: string


jobs:
  trigger-next-workflows:
    runs-on: ubuntu-22.04
    needs:
      - test-base-image
      - test-postgres-integ
    steps:
      - name: Publish images
        uses: ./.github/workflows/90-publish-images.yml

  test-base-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install if required common software tooling
        uses: camunda/infra-global-github-actions/common-tooling@main
        with:
          java-enabled: false
          yarn-enabled: false

      - name: Login to the registry
        uses: docker/login-action@v3
        with:
          registry: ${{ vars.CONTAINER_REGISTRY }}
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # TODO: use current version of the image in the shell
      - name: KeyCloak Show-Config
        run: |
          docker run ${{ inputs.test_image_name }} show-config >> docker.log
          echo "config=$(cat docker.log | tr '\n' ' ')" >> "$GITHUB_ENV"

      - name: Assert Config
        env:
          CONFIG: ${{ env.config }}
        run: python3 ./.github/scripts/build-check/main.py

  test-postgres-integ:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install if required common software tooling
        uses: camunda/infra-global-github-actions/common-tooling@main
        with:
          java-enabled: false
          yarn-enabled: false

      - name: Login to the registry
        uses: docker/login-action@v3
        with:
          registry: ${{ vars.CONTAINER_REGISTRY }}
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Start Test Environment
        uses: ./.github/actions/compose
        with:
          compose_file: ${{ github.workspace }}/docker-compose.yml
          project_name: keycloak
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r ./.github/scripts/integration/requirements.txt
      - name: Test Environment
        run: python3 ./.github/scripts/integration/main.py


# TODO: add tests (static framework tbd) then push
