---
name: publish-images
on:
  workflow_run:
    workflows: ["test-images"]
    types:
      - completed
    branches:
      - main

jobs:
  publish-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
