name: check-unused-resources

on:
  push:
  schedule:
    - cron: "0 0 * * *"

jobs:
  check-unused-databases-aws:
    runs-on: aws-core-2-default
    strategy:
      fail-fast: false # don't propate failing jobs
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install if required common software tooling
        uses: camunda/infra-global-github-actions/common-tooling@main
        with:
          java-enabled: false
          yarn-enabled: false
          python-version: "3.12"

      - name: Drop unused database
        run: |
          sudo apt-get update && sudo apt-get install -y build-essential postgresql-client
          python3 -m pip install awscli

          RETENTION_INTERVAL="2 days"

          # Define the databases in an array
          databases=(
          "camunda-ci-eks-aurora-postgresql-13.cluster-clnwzia8ptad.eu-central-1.rds.amazonaws.com:5432"
          "camunda-ci-eks-aurora-postgresql-14.cluster-clnwzia8ptad.eu-central-1.rds.amazonaws.com:5432"
          "camunda-ci-eks-aurora-postgresql-15.cluster-clnwzia8ptad.eu-central-1.rds.amazonaws.com:5432"
          "camunda-ci-eks-aurora-postgresql-16.cluster-clnwzia8ptad.eu-central-1.rds.amazonaws.com:5432"
          )

          for db in "${databases[@]}"; do
              IFS=':' read -ra db_info <<< "$db"
              PGHOST="${db_info[0]}"
              PGPORT="${db_info[1]}"
              PGDATABASE="postgres"
              PGUSER="keycloak-irsa"
              PGPASSWORD="$(aws rds generate-db-auth-token --hostname "${PGHOST}" --port "${PGPORT}" --region "${AWS_REGION}" --username "${PGUSER}")"
              export PGPASSWORD
              export PGPORT
              export PGUSER
              export PGHOST
              export PGDATABASE
              export RETENTION_INTERVAL
              bash ./.helpers/actions/drop-unused-db.sh
          done
