---
name: infra-checks

on:
  workflow_dispatch:
  pull_request:
  push:
    branches: [main]

jobs:
  actionlint:
    runs-on: ubuntu-latest
    steps:
      - uses: camunda/infra-global-github-actions/actionlint@main
        with:
          custom-config-file: .github/actionlint.yaml
