---
name: Internal - Global - Pull Request TODO checker

# This workflow triggers a scan of TODOs in the current pull request.
# For each TODO that is not marked to be ignored, it posts a comment.
# It helps ensure that no TODOs are accidentally left behind in merged PRs.

on:

    pull_request:
        types: [opened, synchronize, reopened]

concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: false

jobs:
    call-todo-checker:
        uses: camunda/infraex-common-config/.github/workflows/todo-checker-global.yml@ce8f360e366f900378c3d1531d1f278f3789f04b # 1.7.0
        secrets: inherit
