---
name: Integration - Postgresql

on:
  push:

jobs:
  integration:
    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v3
    - name: Install if required common software tooling
      uses: camunda/infra-global-github-actions/common-tooling@main
      with:
        java-enabled: false
        yarn-enabled: false
    - name: Start Test Environment
      uses: ./.github/actions/compose
      with:
        compose_file: ${{ github.workspace }}/docker-compose.yml
        project_name: keycloak
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r ./.github/scripts/integration/requirements.txt
    - name: Test Environment
      run: python3 ./.github/scripts/integration/main.py
