---
name: lint

on:
    workflow_dispatch:
    pull_request:
    push:
        branches: [main]

jobs:
    lint:
        uses: camunda/infraex-common-config/.github/workflows/lint-global.yml@ce8f360e366f900378c3d1531d1f278f3789f04b # 1.7.0
        secrets: inherit
